apiVersion: v1
kind: ConfigMap
metadata:
  name: service-urls
  namespace: microservices
data:
  USER_SERVICE_URL: "http://user-service:8080"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8080"